-- Task Manager v3: Add action_type, priority text mapping, time_slot, etc.
ALTER TABLE items ADD COLUMN IF NOT EXISTS action_type TEXT DEFAULT 'do';
ALTER TABLE items ADD COLUMN IF NOT EXISTS time_slot TEXT DEFAULT 'anytime';
ALTER TABLE items ADD COLUMN IF NOT EXISTS due TEXT;
ALTER TABLE items ADD COLUMN IF NOT EXISTS estimated_minutes INTEGER;
ALTER TABLE items ADD COLUMN IF NOT EXISTS assignee TEXT DEFAULT 'self';
ALTER TABLE items ADD COLUMN IF NOT EXISTS contact_persons JSONB DEFAULT '[]'::jsonb;
ALTER TABLE items ADD COLUMN IF NOT EXISTS sub_category TEXT;
ALTER TABLE items ADD COLUMN IF NOT EXISTS project TEXT;
ALTER TABLE items ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false;
ALTER TABLE items ADD COLUMN IF NOT EXISTS is_focus BOOLEAN DEFAULT false;
ALTER TABLE items ADD COLUMN IF NOT EXISTS focus_order INTEGER DEFAULT 0;
